### ISSUE TITLE
Supplies and other information are not being correctly shown on mobile browsers.

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#80]
![2023-06-09 12 26 37](https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/1809436/f27fc15e-d50b-4f3d-83bf-8fda39cbfc29)

Even if the user cannot connect a wallet using a mobile browser, we should still show correct information about, for instance, the prices and supplies.

**Comment by a-singh09** [comment]
Hi, the issue is caused due to this check
```
if (window.ethereum) {
      try {
        const web3 = new Web3(BLOCKCHAIN_URI);
        resolve(web3);
      } catch (error) {
        reject(error);
      }
    }
```
  
But `BLOCKCHAIN_URI` is the RPC Provider url, so it does not depend on `window.ethereum` at all. Also checks are already available for critical functions if wallet is connected or not.

So we can safely remove the `if` condition. This will show correct information about the prices and supplies even on devices in which metamask is not installed like mobile devices.

**Comment by ceilican** [comment]
Great, @a-singh09 . Could you submit a PR that fixes this issue?
